class BotecoGem
  
  def self.name
    return [
      "Abençoado",
      "Acionista",
      "Afortunado",
      "Afrontoso",
      "Almirante",
      "Ameríndio",
      "Amigão",
      "Amigo Charlie Brown",
      "Amoroso",
      "Antagonista",
      "Antropófago",
      "Arduíno",
      "Aristocrata",
      "Arrojado",
      "Artilheiro",
      "Associado",
      "Avassalador",
      "Bacana",
      "Bacano",
      "Bacharel",
      "Balaústre",
      "Baluarte",
      "Barroco",
      "Benevolente",
      "Bigode",
      "Bolivariano",
      "Bon Vivant",
      "Bona Fé",
      "Bonachão",
      "Brother",
      "Cabriolet",
      "Camarada",
      "Camisa 10",
      "Campeão",
      "Camponês",
      "Cantochão",
      "Capitão",
      "Carnavalesco",
      "Celibatário",
      "Chanceler",
      "Chapa",
      "Charmoso",
      "Chefia",
      "Comandante",
      "Combatente",
      "Comediante",
      "Companheiro",
      "Comtemporâneo",
      "Coronel",
      "Correligionário",
      "Cosmopolita",
      "Delator",
      "Dementador",
      "Democrata",
      "Desbravador",
      "Diamante",
      "Diplomata",
      "Dramaturgo",
      "Ébano",
      "Eclesiasta",
      "Eloquente",
      "Emancipado",
      "Emissário",
      "Encantador",
      "Enquirídio",
      "Entrepeneur",
      "Escrivão",
      "Estrategista",
      "Estruturalista",
      "Estupendo",
      "Extravagancia",
      "Extravagante",
      "Famigerado",
      "Fashionista",
      "Federado",
      "Fera",
      "Fidedigno",
      "Filantropo",
      "Formoso",
      "Garanhão",
      "Generoso",
      "Gerente",
      "Grã-Fino",
      "Guardião",
      "Historiador",
      "Homologado",
      "Humorista",
      "Iluminado",
      "Ilusionista",
      "Ilustre",
      "Imaculado",
      "Inadimplente",
      "Influencer",
      "Inoxidável",
      "Inquisitor",
      "Jesuíta",
      "Legatário",
      "Litorâneo",
      "Maestro",
      "Magnata",
      "Mascarado",
      "Messias",
      "Mestre",
      "Mionzera",
      "Monarca",
      "Navegante",
      "Nego Fera",
      "Nórdico",
      "Palestrinha",
      "Patrão",
      "Pecado",
      "Peregrino",
      "Persuasivo",
      "Pierrot",
      "Piloto",
      "Politeísta",
      "Pós-moderno",
      "Pragmático",
      "Procarionte",
      "Promotor",
      "Protagonista",
      "Queridão",
      "Quirografário",
      "Resplandecente",
      "Reverendo",
      "Roshan",
      "Saboteur",
      "Sambarilove",
      "Secular",
      "Sensei",
      "Soberbo",
      "Sócio",
      "Socrático",
      "Soturno",
      "Talentoso",
      "Tórrido",
      "Trequartista",
      "Tributarista",
      "Tupã",
      "Tupi-Guarani",
      "Valoroso",
      "Vanguardista",
      "Xamã",
      "Xará",
      "Zagueiro",
    ].sample

  end

  def self.greetings
    return [
      "Opa",
      "Ei",
      "Psiu",
      "Ou",
      "Salve",
      "Alô",
      "Ô",
      "Fala"
    ].sample
  end

  def self.action
    return [
      "Desce mais uma rodada!",
      "Desce mais uma",
      "Traz a saidêrá",
      "Me vê o supra-sumo",
      "Solta a gelada",
      "Traz um refil",
      "Me dá uma benção!",
      "Conceda sua graça",
      "Manda aquela",
      "Solta já trincando"
     ].sample
  end

  def self.chamarGarcom
    return "#{greetings} meu #{name.downcase}! #{action}!"
  end

  def self.drunk
    return "(#{"#{greetings} meu #{name.downcase.reverse} hic! #{action.reverse} hic!"})"
  end

end

p BotecoGem.drunk