class BotecoGem
  
  def self.chamarGarcom

  end

  def self.name
    return [
      "Persuasivo",
      "Estrategista",
      "Delator",
      "Inadimplente",
      "Ilusionista",
      "Politeísta",
      "Vigilante",
      "Tupã",
      "Quirografário",
      "Inquisidor",
      "Desbravador",
      "Influencer",
      "Litorâneo",
      "Maestro",
      "Garanhão",
      "Pecado",
      "Camponês",
      "Peregrino",
      "Tributarista",
      "Historiador",
      "Secular",
      "Comediante",
      "Incorreto",
      "Cantochão",
      "Tórrido",
      "Promotor",
      "Patrão",
      "Acionista",
      "Arduíno",
      "Balaústre",
      "Companheiro",
      "Escrivão",
      "Roshan",
      "Piloto",
      "Inoxidável",
      "Celibatário",
      "Amoroso",
      "Tupi-Guarani",
      "Afrontoso",
      "Sensei",
      "Palestrinha",
      "Antagonista",
      "Gerente",
      "Jesuíta",
      "Antropófago",
      "Mionzera",
      "Zagueiro",
      "Pragmático",
      "Nórdico",
      "Extravagante",
      "Extravagancia",
      "Dramaturgo",
      "Combatente",
      "Pierrot",
      "Monarca",
      "Ébano",
      "Bonachão",
      "Saboteur",
      "Mascarado",
      "Imaculado",
      "Aristocrata",
      "Correligionário",
      "Benevolente",
      "Afortunado",
      "Fashionista",
      "Resplandecente",
      "Cabriolet",
      "Avassalador",
      "Socrático",
      "Filantropo",
      "Diamante",
      "Homologado",
      "Reverendo",
      "Trequartista",
      "Procarionte",
      "Arrojado",
      "Carnavalesco",
      "Federado",
      "Sócio",
      "Associado",
      "Xamã",
      "Formoso",
      "Capitão",
      "Enquirídio",
      "Humorista",
      "Messias",
      "Comandante",
      "Talentoso",
      "Democrata",
      "Bacharel",
      "Pós-moderno",
      "Comtemporâneo"
      "Diplomata",
      "Bolivariano",
      "Amigo Charlie Brown",
      "Iluminado",
      "Valoroso",
    ].sample
  end

  def self.greetings
    return [
      "Opa",
      "Ei",
      "Psiu",
      "Ou",
      "Fera",
      "Salve",
      "Alô",
      "Ô",
      "And then you get an error message in your pretty face!",
      "Dude writes Ruby on RAILS and draws a HIGHWAY.",
      "It makes no sense what you're doing!",
      "Can do, you can, you may, but I cannot understand why someone would do it.",
      "Copy is the first step to creation.",
      "There are no limits to the creativity of the human being.",
      "Today is a great day to code.",
      "The important thing about rules is knowing when to break them",
      "It's life what gives you the real Reboot.",
      "It doesn't make sense! He wants to exchange six for a half dozen!!",
      "It only takes 15 minutes to learn scrum, lol",
      "Life is too short to waste it coding in Java.",
      "Open Source is the most efficient software ever"
    ].sample
  end

  def self.action
    return [
      "Desce mais uma!",
      "Trás a saidêrá!",
      "Me vê o supra-sumo!"
     ].sample
  end
end

p BotecoGem.name